### ISSUE TITLE
Getting FreemarkerProcessor$FreemarkerProcessingFailed when report is generated

### ISSUE THREAD

**Issue by mdzhigarov** [jbehave/jbehave-core#55]
I'm getting some odd exception in one of my stories.
Using jBehave 5.0

This is how my configuration looks like:
```
@Override
    public Configuration configuration() {
        Class<? extends Embeddable> embeddableClass = this.getClass();
        // Start from default ParameterConverters instance
        ParameterConverters parameterConverters = new ParameterConverters();
        // factory to allow parameter conversion and loading from external
        // resources (used by StoryParser too)

        return new MostUsefulConfiguration()
                .useStoryControls(new StoryControls().doDryRun(false).doSkipScenariosAfterFailure(false))
                .useStoryLoader(new LoadFromClasspath(embeddableClass))
                .useStoryPathResolver(new UnderscoredCamelCaseResolver())
                .useStoryReporterBuilder(
                        new StoryReporterBuilder()
                                .withCodeLocation(CodeLocations.codeLocationFromClass(embeddableClass))
                                .withSurefireReporter(new SurefireReporter(embeddableClass))
                                .withDefaultFormats().withPathResolver(new ResolveToPackagedName())
                                .withFormats(CONSOLE, TXT)
                                .withFailureTrace(true)
                                .withFailureTraceCompression(true))
                .useParameterConverters(parameterConverters);
    }
```    
    
    
The exception I'm getting:

```
org.jbehave.core.embedder.Embedder$ViewGenerationFailed: View generation failed to C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave for formats [stats, console, txt] and resources {reports=ftl/jbehave-reports.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl, maps=ftl/jbehave-maps.ftl, views=ftl/jbehave-views.ftl, decorated=ftl/jbehave-report-decorated.ftl}

	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:277)
	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:262)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:222)
	at org.jbehave.core.junit.JupiterStories.run(JupiterStories.java:22)
	at com.mdzh.admiral.request.genericallocation.GenericAllocationTaskE2EStoryTest.runStory(GenericAllocationTaskE2EStoryTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.jbehave.core.reporters.TemplateableViewGenerator$ReportCreationFailed: Report creation failed from file {AfterStories=[C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\AfterStories.stats, C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\AfterStories.txt], BeforeStories=[C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\BeforeStories.stats, C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\BeforeStories.txt], jbehave.generic_allocation_group_id_calculation=[C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\jbehave.generic_allocation_group_id_calculation.stats, C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\jbehave.generic_allocation_group_id_calculation.txt], jbehave.generic_allocation_task_already_executed=[C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\jbehave.generic_allocation_task_already_executed.stats, C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\jbehave.generic_allocation_task_already_executed.txt], jbehave.generic_allocation_task_е2е=[C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\jbehave.generic_allocation_task_е2е.stats, C:\Users\mdzhigarov\git\provisioning-service\request\target\jbehave\jbehave.generic_allocation_task_е2е.txt]}
	at org.jbehave.core.reporters.TemplateableViewGenerator.createReports(TemplateableViewGenerator.java:247)
	at org.jbehave.core.reporters.TemplateableViewGenerator.generateReportsView(TemplateableViewGenerator.java:128)
	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:274)
	... 38 more
Caused by: org.jbehave.core.reporters.TemplateableViewGenerator$ViewGenerationFailedForTemplate: ftl/jbehave-report-decorated.ftl
	at org.jbehave.core.reporters.TemplateableViewGenerator.write(TemplateableViewGenerator.java:293)
	at org.jbehave.core.reporters.TemplateableViewGenerator.createReports(TemplateableViewGenerator.java:240)
	... 40 more
Caused by: org.jbehave.core.reporters.FreemarkerProcessor$FreemarkerProcessingFailed: Freemarker failed to process template ftl/jbehave-report-decorated.ftl using configuration freemarker.template.Configuration@3ae7dc1f and data model {name=jbehave.generic_allocation_task_е2е, format=stats, body=#org.jbehave.core.reporters.PostStoryStatisticsCollector
#Thu Nov 24 18:30:15 EET 2022
scenariosExcluded=0
comments=0
scenariosPending=0
pending=0
stepsFailed=0
scenarios=1
stepsSuccessful=13
stepsIgnorable=0
givenStoryScenariosSuccessful=0
steps=13
givenStoryScenariosPending=0
excluded=0
givenStoryScenarios=0
scenariosFailed=0
examples=0
stepsPending=0
scenariosSuccessful=1
stepsNotPerformed=0
givenStoryScenariosExcluded=0
givenStories=0
givenStoryScenariosFailed=0
}
	at org.jbehave.core.reporters.FreemarkerProcessor.process(FreemarkerProcessor.java:30)
	at org.jbehave.core.reporters.TemplateableViewGenerator.write(TemplateableViewGenerator.java:289)
	... 41 more
	Suppressed: java.nio.charset.UnmappableCharacterException: Input length = 1
		at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:275)
		at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:306)
		at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
		at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
		at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:211)
		at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
		at java.base/java.io.BufferedWriter.close(BufferedWriter.java:268)
		at org.jbehave.core.reporters.TemplateableViewGenerator.write(TemplateableViewGenerator.java:288)
		... 41 more
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:275)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:306)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:211)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:256)
	at freemarker.core.Environment.process(Environment.java:329)
	at freemarker.template.Template.process(Template.java:383)
	at org.jbehave.core.reporters.FreemarkerProcessor.process(FreemarkerProcessor.java:28)
	... 42 more

```

I'm not getting this for any of my other stories and I don't understand what's so special about this story in particular. It's almost identical to the other ones.
Any help will be appreciated...

**Comment by mdzhigarov** [comment]
This is how the dataModel value within the FreemarkerProcessor looks like:

```
<div id="dc467412-2f3e-4271-a495-48fd987baa25" class="story">
<h1></h1>
<div class="path">jbehave/generic_allocation_task_Ðµ2Ðµ.story</div>
<div class="beforeSystemStorySteps">
</div>
<div class="beforeUserStorySteps">
</div>
<div id="c144e269-5dd0-4d21-94f9-554ed0851102" class="scenario">
<h2>Scenario: Testing that if an allocation task has already been executed for an allocation resource in
the same group - the task won't perform allocation again.</h2>
<div class="beforeSystemScenarioSteps">
</div>
<div class="beforeUserScenarioSteps">
</div>
<div class="steps">
<div class="step successful">Given Resource_A depending on ComputeAllocation_A</div>
<div class="step successful">And Endpoint <span class="step parameter">1</span> of type <span class="step parameter">aws</span></div>
<div class="step successful">And Region <span class="step parameter">us-west-1</span> in endpoint <span class="step parameter">1</span></div>
<div class="step successful">And Compute <span class="step parameter">us-west1-a</span> in region <span class="step parameter">us-west-1</span></div>
<div class="step successful">And Placement Zone <span class="step parameter">1/us-west-1</span> with computes <span class="step parameter">us-west1-a</span></div>
<div class="step successful">When GenericAllocationTaskService_A is executed with <span class="step parameter">ComputeAllocation_A</span></div>
<div class="step successful">Then the groupId of the GenericAllocationTaskService_A is not null</div>
</div>
<div class="afterUserScenarioSteps">
</div>
<div class="afterSystemScenarioSteps">
<div class="step successful">com.mdzh.admiral.request.genericallocation.steps.GenericAllocationTaskSteps.cleanUp()</div>
<div class="step successful">com.mdzh.admiral.request.genericallocation.steps.PlacementZoneSteps.cleanUp()</div>
<div class="step successful">com.mdzh.admiral.request.genericallocation.steps.PlacementComputeSteps.cleanUp()</div>
<div class="step successful">com.mdzh.admiral.request.genericallocation.steps.RegionSteps.cleanUp()</div>
<div class="step successful">com.mdzh.admiral.request.genericallocation.steps.EndpointSteps.cleanUp()</div>
<div class="step successful">com.mdzh.admiral.request.genericallocation.steps.AllocationResourceSteps.cleanUp()</div>
</div>
<h3>start 1669308401075</h3>
<h3>end 1669308401634</h3>
</div>
<div class="afterUserStorySteps">
</div>
<div class="afterSystemStorySteps">
</div>
</div>

```

It seems there was a cyrillic symbol in the story name generic_allocation_task_Ðµ2Ðµ.story

After renaming the story all works as expected. 
Please close the issue if you consider this to be a user error. Otherwise I think it might be beneficial to fix the error handling so it's more obvious what's the issue.

**Comment by valfirst** [comment]
@mdzhigarov what was the actual story name? which charset do you use for it?

**Comment by mdzhigarov** [comment]
It was generic_allocation_task_е2е.story but it seems the "e" symbol was the cyrillic "e" which is slightly different - "е"

**Comment by dejan-kosak** [comment]
Did you fix that, by setting encoding? I have similar issue because of non standard chars. I don't know how to set encoding exactly. I tried with setting property, but is does not help. 
https://jbehave.org/reference/latest/stories-in-your-language.html

**Comment by valfirst** [comment]
@dejan-kosak you need to configure charset in `ViewGenerator`, e.g.:
```java
ViewGenerator viewGenerator = new FreemarkerViewGenerator(
    new UnderscoredToCapitalized(),
    FreemarkerViewGenerator.class,
    StandardCharsets.UTF_8
);
configuration.useViewGenerator(viewGenerator)
```
